name: Biome Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  biome-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-depedencies]

      - name: Run Biome check
        run: pnpm exec biome check .
